baseURL = "https://juliagdealedo.github.io"
languageCode = "en-US"
title = "Julia G. de Aledo"

enableEmoji = true
enableRobotsTXT = true

disableKinds = ['taxonomy', 'term']

[permalinks]
about = "about"
projects = "/:slug/"

[author]
name = "Julia G. de Aledo"
image = "img/author.jpg"
bio = "PhD in tropical ecology and ethnobotany"
links = [
  { twitter = "https://twitter.com/juliagdealedo" },
  { email = "mailto:julia.gonzalezdealedo@uam.es" },
  { linkedin = "https://www.linkedin.com/in/g-de-aledo-julia-99ba55140/" },
  { youtube = "https://www.youtube.com/channel/UCgnkevuKdftZyKzGHGEVNSg/featured" }
]


[markup.goldmark.renderer]
unsafe = true
