baseURL = "https://juliagdealedo.github.io"
languageCode = "en-US"
title = "Julia G. de Aledo"

enableEmoji = true
enableRobotsTXT = true

disableKinds = ['taxonomy', 'term']

[permalinks]
about = "about"
projects = "/:slug/"

[author]
name = "Julia G. de Aledo"
image = "img/author.jpg"
bio = "PhD student at Universidad Autónoma de Madrid."
links = [
  { twitter = "https://twitter.com/juliagdealedo" },
  { email = "mailto:julia.gonzalezdealedo@uam.es" },
  { linkedin = "https://linkedin.com/" },
  { youtube = "https://www.youtube.com/channel/UCgnkevuKdftZyKzGHGEVNSg/featured" }
]
