[[main]]
  name = "About me"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "Publications"
  pageRef = "publications"
  weight = 30

[[main]]
  name = "Code"
  pageRef = "code"
  weight = 40

[[main]]
  name = "Illustrations"
  pageRef = "illustrations"
  weight = 50
